#159965301 Write descriptive registration validation errors
andela/ah-magnificent6 pull request #18
Opened 2018-09-05 13:18 UTC by micahoriaso

#### What does this PR do?
- Write descriptive validation error messages for user registration

#### Description of Task to be completed?
- Give an error message when a user tries to register with an email that has already been used
- Give an error message when a user tries to register with a username that has already been used
- Give an error message when the user tries to register with an inavlid email address
- Give an error message when the user tries to register with apass word that is less than eight characters long
- Give an error message when the user tries to register with a password that is not alphanumeric

#### How should this be manually tested?
$ git clone https://github.com/andela/ah-magnificent6.git
$ cd ah-magnificent6
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install -r requirements.txt
(venv) $ python manage.py migrate
(venv) $ python manage.py runserver
Using [Postman](https://www.getpostman.com/) navigate to 

> {your-server-root}:8000/api/users/signup/

with this payload

```
{
"email":"your-email-here",
"username":"your-username",
"password":"your-password"
}
```

#### What are the relevant pivotal tracker stories?
[#159965301](https://www.pivotaltracker.com/story/show/159965301)
#### Screenshots
<img width="1680" alt="screen shot 2018-09-05 at 16 12 22" src="https://user-images.githubusercontent.com/20840601/45095658-45f00980-b127-11e8-9a5b-c5aa9da86efb.png">
<img width="1680" alt="screen shot 2018-09-05 at 16 12 50" src="https://user-images.githubusercontent.com/20840601/45095659-45f00980-b127-11e8-8a4f-e096400fd800.png">
<img width="1680" alt="screen shot 2018-09-05 at 16 16 03" src="https://user-images.githubusercontent.com/20840601/45095660-45f00980-b127-11e8-9d22-4b5acb51a0f6.png">

2018-09-05 13:26 UTC, micahoriaso commented
@PAbishai, @meshack-mbuvi kindly take time to review this Pull Request

2018-09-05 13:39 UTC, PAbishai commented
@micahoriaso based on your description we will be testing develop

2018-09-05 14:53 UTC, meshack-mbuvi commented
Am just curious, do we need to send `username` and `email` to users as a response when they create their accounts? I am in the opinion of just sending to them a welcome message and token.

2018-09-05 15:10 UTC, pabishai commented on authors/apps/authentication/views.py
> +            'username', None), request.data.get('password', None)
@micahoriaso is this assignment pep8 standards?

2018-09-05 19:14 UTC, meshack-mbuvi commented
Please add a step to set the environmental variables for the project. Without it, people may not know whether they should have the configurations for the DATABASE and SECRET_KEY.

2018-09-05 19:17 UTC, meshack-mbuvi commented on authors/apps/authentication/views.py
> +            'username', None), request.data.get('password', None)
I think it does not violate pep8 standard

2018-09-06 06:01 UTC, micahoriaso commented
@meshack-mbuvi  the environment variables issue has been resolved

2018-09-06 06:02 UTC, micahoriaso commented
@PAbishai I have included the feature branch step in the pull request

2018-09-06 06:04 UTC, micahoriaso commented on authors/apps/authentication/views.py
> +            'username', None), request.data.get('password', None)
@PAbishai yes, this follows pep8 standards.

2018-09-06 09:27 UTC, parseen254 requested changes

2018-09-06 09:27 UTC, parseendavid commented on authors/apps/authentication/serializers.py
> +        email = data.get('email', None)
@micahoriaso This can be compressed to a single line variable assignment. i.e a,b = valueA, valueB

2018-09-10 05:55 UTC, PAbishai commented
It works as expected

2018-09-10 08:31 UTC, parseen254 requested changes

2018-09-10 08:31 UTC, parseendavid commented on authors/apps/authentication/tests/test_registration.py
> +        """ Test that a user enters a password with numbers only """
@micahoriaso make sure the descriptions are in sync with the implementation.

2018-09-11 06:30 UTC, parseen254 approved these changes

2018-09-11 06:31 UTC, merged