[Feature #159965314] List users functionality
andela/ah-magnificent6 pull request #41
Opened 2018-09-18 09:02 UTC by mikenthiwa

#### What does this PR do?
Allows authenticated users to list profiles of all authors.

#### Description of Task to be completed?
A user is able to view all profiles of all authors and is not able to edit the profiles profiles

#### How should this be manually tested?
$ git clone https://github.com/andela/ah-magnificent6.git
$ git checkout ft-list-user-functionality-159965314
$ cd ah-magnificent6
$ cp .env-sample .env [and set the environment variables]
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install -r requirements.txt
(venv) $ python manage.py migrate
(venv) $ python manage.py runserve

Using [Postman](https://www.getpostman.com/) navigate to 
User registration: `POST {your-server-root}:8000/api/user/signup`
```
{
    "email": "user1@user.user",
    "username": "user1",
    "password": "User$#@!"
}
```
User Login: `POST {your-server-root}:8000/api/user/login`
```
{
    "email": "user1@user.user",
    "password": "User$#@!"
}
```

Use the token from the response in the login as the authentication header while listing all authors

List all authors
In Postman client: `GET {your-server-root}:8000/api/profiles/authors`
<img width="990" alt="screen shot 2018-09-18 at 11 52 16" src="https://user-images.githubusercontent.com/30254491/45676509-8d6c9180-bb3a-11e8-8e03-7b8ba15a4536.png">

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2192364/stories/159965314

2018-09-18 09:41 UTC, meshack-mbuvi commented
I have noted that our coverage is complaining. Please fix that as we agreed to keep it up. Meanwhile, I will be going through your code.

2018-09-18 10:34 UTC, mikenthiwa commented
@meshack-mbuvi 
Test coverage has been improved.
Kindly continue going through the PR.

2018-09-18 10:52 UTC, meshack-mbuvi commented
It looks good to me unless have missed something.

2018-09-18 12:51 UTC, pngg commented
looks good to me too :)

2018-09-19 13:19 UTC, parseen254 requested changes
Also, squash your migrations. Recommended resource: https://stackoverflow.com/questions/40028586/how-to-squash-recent-django-migrations

2018-09-19 13:19 UTC, parseen254 commented on authors/settings.py
> +    'PAGE_SIZE': 10
@mikenthiwa why was this reduced?

2018-09-19 17:37 UTC, mikenthiwa commented on authors/settings.py
> +    'PAGE_SIZE': 10
I was testing my feature using a page size of 10.
I will revert it to 20 since it works fine

2018-09-20 05:06 UTC, mikenthiwa commented on authors/settings.py
> +    'PAGE_SIZE': 10
@parseendavid Returned page size to 20
Squashed migrations

2018-09-20 09:12 UTC, merged