Configure Database and set up environment variable
andela/ah-magnificent6 pull request #5
Opened 2018-08-28 14:35 UTC by mikenthiwa

What does this PR do?
  * Create environment setting and configure AuthorsHaven app to use PostgreSQL as DB Engine.

Description of Task to be completed?
  * Using `Twelve-factor methodology`_ to configure the application with environment variables.
  * Install Psycopg2.
  * Changed Engine to 'django.db.backends.postgresql_psycopg2.

What are the relevant pivotal tracker stories?
  * [Configure Authors Haven to use PostgreSQL as DB Engine](https://www.pivotaltracker.com/story/show/159965295)

2018-08-28 15:00 UTC, meshack-mbuvi commented on authors/settings.py
> +import dj_database_url
I have noted that you have installed and imported dj_database_url but you are not using it.

2018-08-28 15:03 UTC, mikenthiwa commented on authors/settings.py
> +import dj_database_url
Noted and rectified

2018-08-28 16:11 UTC, Bileonaire commented
I have checked out the changes made. Good work on setting up the environment variables(.env file).

 You can create a  .env_sample file for us to be able to use.

2018-08-28 17:09 UTC, parseen254 reviewed
@Bileonaire the env-sample file does not need to be a bash file.....

2018-08-28 17:26 UTC, parseendavid commented
Also adhere to this while naming your branches and PR's
 https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

2018-08-29 05:55 UTC, PAbishai commented
@mikenthiwa Consider adding a way to manually test it. I cannot assert that the database connection works as it is.

2018-08-29 06:01 UTC, micahoriaso commented
@mikenthiwa please let us not create pull requests that merge into master

2018-08-29 06:18 UTC, pngg commented on authors/settings.py
> +root = environ.Path(__file__) - 2  # three folder back (/a/b/c/ - 3 = /)
I've noticed that the ROOT path has been defined twice. ie BASE_DIR and this 'root' variable. Could we please refactor and use the BASE_DIR instead? Also, let's define such constants with all caps.

2018-08-29 06:43 UTC, mikenthiwa commented
I have implemented the required changes.

2018-08-29 09:36 UTC, parseen254 requested changes
@mikenthiwa why does the env-sample file have to be a bash script?

2018-08-29 09:36 UTC, parseen254 commented on authors/settings.py
> +    'default': env.db()
Are you sure this will work?

2018-08-29 09:56 UTC, mikenthiwa commented on authors/settings.py
> +    'default': env.db()
I have disscussed with my peer and he encountered a problem when using the bash script.
I will use .env
I am pushing the changes immediately

2018-08-29 10:53 UTC, pngg approved these changes
The settings seem ok now.

2018-08-30 05:47 UTC, parseen254 approved these changes

2018-08-30 05:49 UTC, merged