Feature #159965321 Add report article
andela/ah-magnificent6 pull request #53
Opened 2018-09-21 07:14 UTC by micahoriaso

#### What does this PR do?
- Enable users to report articles

#### Description of task to be completed?
- Give authenticated users the ability to report articles that violate the terms and conditions of Authors' Haven

#### How should this be manually tested?
$ git clone https://github.com/andela/ah-magnificent6.git
$ git checkout ft-report-article-159965321
$ cd ah-magnificent6
$ cp .env-sample .env [and set the environment variables]
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install -r requirements.txt
(venv) $ python manage.py migrate
(venv) $ python manage.py runserver
Using [Postman](https://www.getpostman.com/) navigate to 
User registration: `POST {your-server-root}:8000/api/user/signup`
```
{
    "email": "author@user.user",
    "username": "author",
    "password": "good123456"
}
```

User Login: `POST {your-server-root}:8000/api/user/login`
```
{
    "email": "author@user.user",
    "password": "good123456"
}
```
Use the token from the response in the login as the authentication header while creating an article.

<img width="1388" alt="screen shot 2018-09-12 at 10 54 16" src="https://user-images.githubusercontent.com/39065274/45410426-500b8e00-b67a-11e8-91ed-49338b9f3ab3.png">

Create article : POST {your-server-root}:8000/api/articles/
```
{
"title": "My Journey to Andela",
 "description": "This article is about how I joined Andela",
"body": "This is my story to Andela"
}
```
#### Report Article
> POST {your-server-root}:8000/api/articles/`<article-slug>`/report

```
{
   'text': 'This article is plagiarised'
}
```
Expect this response
```
{
    "Articles": {
        "message": "Your feedback has been recorded. Authors' Haven thanks you for your service."
    }
}
```
#### List All Article Reports
> GET {your-server-root}:8000/api/articles/`<article-slug>`/report

Expect this response
```
{
    "Articles": [
        {
            "id": 7,
            "text": "Blah blah qwerty",
            "article": 8,
            "user": 1
        },
        {
            "id": 3,
            "text": "This article is discriminates",
            "article": 8,
            "user": 1
        },
        {
            "id": 2,
            "text": "This article is extremely inappropriate",
            "article": 8,
            "user": 1
        }
    ]
}
```

#### Update Article Report
> PUT {your-server-root}:8000/api/articles/`<article-slug>`/report/1

```
{
   'text': 'This article is highly plagiarised'
}
```
Expect this response
```
{
    "Article": {
        "id": 2,
        "text": "This article is highly plagiarised",
        "article": 8,
        "user": 1
    }
}
```

#### DELETE Article Report
> DELETE {your-server-root}:8000/api/articles/`<article-slug>`/report/1

Expect this response
```
{
    "Articles": {
        "message": "Report was deleted successfully"
    }
}
```

#### Retrieve Article Report
> DELETE {your-server-root}:8000/api/articles/`<article-slug>`/report/1

Expect this response
```
{
    "Article": {
        "id": 7,
        "text": "Blah blah qwerty",
        "article": 8,
        "user": 1
    }
}
```

#### What are the relevant pivotal tracker stories?
[#159965321](https://www.pivotaltracker.com/story/show/159965321)

#### Background Context
The user can only report an article a maximum of five times

2018-09-21 07:58 UTC, Bileonaire commented
Good work. Kindly restrain from revealing the id of the article in the response. Store the article object in the Database as the foreign key but just reveal the title or slug.

2018-09-21 08:11 UTC, pngg commented
To second on what Leon has said, could we also return the `username` instead of the `user id` in the response?

2018-09-24 07:16 UTC, micahoriaso commented
@Bileonaire and @pngg  your requests have been worked on. Thanks for your feedback.

2018-09-24 08:02 UTC, parseen254 requested changes

2018-09-24 08:02 UTC, parseen254 commented on authors/apps/articles/views.py
> +        """Method for reporting an article."""
@micahoriaso Which of these two docstrings is unnecessary?

2018-09-24 08:02 UTC, parseendavid commented on authors/apps/articles/views.py
> +    def get_object(self, pk):
@micahoriaso The name for this method is quite ambiguous.

2018-09-24 11:15 UTC, parseen254 approved these changes

2018-09-24 14:46 UTC, merged