Ft comment article 159965308
andela/ah-magnificent6 pull request #56
Opened 2018-09-21 08:10 UTC by mikenthiwa

#### What does this PR do?
- Allows users to comment on articles.

#### Description of task to be completed?
- A user is able to add, get and delete a comment.

#### How should this be manually tested?
$ git clone https://github.com/andela/ah-magnificent6.git
$ git checkout ft-comment-article-159965308
$ cd ah-magnificent6
$ cp .env-sample .env [and set the environment variables]
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install -r requirements.txt
(venv) $ python manage.py migrate
(venv) $ python manage.py runserver

Using [Postman](https://www.getpostman.com/) navigate to 
User registration: `POST {your-server-root}:8000/api/user/signup`

```
{
    "email": "user1@user.user",
    "username": "user1",
    "password": "User$#@!"
}
```

User Login: `POST {your-server-root}:8000/api/user/login`
```
{
    "email": "user1@user.user",
    "password": "User$#@!"
}

```
Use the token from the response in the login as the authentication header while creating, retrieving and deleting a comment.
**Create a comment**
`POST
http://127.0.0.1:8000/api/articles/slug/comments/
`
<img width="929" alt="screen shot 2018-09-21 at 11 08 37" src="https://user-images.githubusercontent.com/30254491/45868564-c309b880-bd8e-11e8-8635-1f8c1366ceab.png">

**Get a comment**
`GET
http://127.0.0.1:8000/api/articles/slug/comments/comment_id/
`
<img width="751" alt="screen shot 2018-09-21 at 11 04 06" src="https://user-images.githubusercontent.com/30254491/45868408-3e1e9f00-bd8e-11e8-8211-957310eeb3ba.png">

**Delete a comment**
`DELETE
http://127.0.0.1:8000/api/articles/slug/comments/comment_id/
`

2018-09-21 13:06 UTC, Bileonaire requested changes

2018-09-21 13:06 UTC, Bileonaire commented on authors/apps/articles/views.py
> +
Kindly fix the indentation here.

2018-09-21 13:06 UTC, Bileonaire commented on authors/apps/articles/tests/test_comments.py
> +        self.detail_comment = reverse('articles:comment_detail', kwargs={"slug": self.slug.data['slug'], "pk": 2})
Kindlly fix the indentation here

2018-09-24 07:12 UTC, mikenthiwa commented on authors/apps/articles/views.py
> +
@Bileonaire Done

2018-09-24 07:57 UTC, micahoriaso commented
<img width="713" alt="screen shot 2018-09-24 at 10 55 15" src="https://user-images.githubusercontent.com/20840601/45941773-5b4eaa00-bfe8-11e8-929a-84deb50cf93b.png">
@mikenthiwa please give the user a descriptive response when there are no comments to show.

2018-09-24 08:03 UTC, micahoriaso commented
<img width="1351" alt="screen shot 2018-09-24 at 11 01 29" src="https://user-images.githubusercontent.com/20840601/45941991-4292c400-bfe9-11e8-8400-ce6e6dc7e8cc.png">
When the user tries to comment on a non existent article this is the error he/she gets. Please try to capture this and give the user an appropirate message.

2018-09-24 13:03 UTC, pngg commented
Looks good to me just needs the rebasing.

2018-09-24 13:49 UTC, mikenthiwa commented on authors/apps/articles/tests/test_comments.py
> +        self.detail_comment = reverse('articles:comment_detail', kwargs={"slug": self.slug.data['slug'], "pk": 2})
@Bileonaire done

2018-09-24 13:50 UTC, Bileonaire approved these changes

2018-09-25 08:26 UTC, merged