159965320 allow users to bookmark articles
andela/ah-magnificent6 pull request #57
Opened 2018-09-24 07:16 UTC by meshack-mbuvi

#### What does this pull request do?
- Enable users to bookmark an article
- Enable users to retrieve and delete their bookmarks

#### Description of tasks to be completed
- Ensure to have tests for bookmarking, retrieving and deleting an article bookmark
- Add views, serializers, and URLs to bookmark, retrieve and delete an article bookmark

#### How should this be manually tested?
- Clone [this](https://github.com/andela/ah-magnificent6.git) repository
- Copy everything on *.env-sample* to  *.env* [and set the environment variables]
- Create and activate a [virtual environment](https://docs.python.org/3/library/venv.html) inside the project base directory.
- Run the command `git checkout ft-bookmark-articles-159965320`
- Install the project dependencies by running `pip install -r requirements.txt`
- Run the server by issuing the command `python manage.py runserver`
- Using ([Postman](https://www.getpostman.com/) or your favorite REST API client, 
- Create an account by accessing `api/users/signup/` by sending the payload in the format`
`{
  "firstname": "admin",
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "password",
} 
`
and 
login on `/api/users/login/` using the same format for the payload above
- test the above endpoints by passing data in the format 
`{
    'title':'title of the article',
    'body':'body of the article',
    'description':'Description of the article'
}`
- Now that you have created an article, visit `http://127.0.0.1:8000/api/articles/slug/bookmarks` to bookmark the article created above
- To retrieve or delete your bookmarks, visit`http://127.0.0.1:8000/api/articles/bookmarks/{bookmark_id}` using `get` method to retrieve a bookmark or `delete` method to delete your bookmark.
**Note** Visiting `http://127.0.0.1:8000/api/articles/bookmarks/` using `get` retrieves all your bookmarks while using `delete` deletes all your bookmarks

#### What are the relevant pivotal tracker stories?
[#159965320 Users can bookmark an article](https://www.pivotaltracker.com/story/show/159965320)

#### Screenshots
![image](https://user-images.githubusercontent.com/9263906/45940520-3f480a00-bfe2-11e8-8d19-55d87eec0b38.png)
![image](https://user-images.githubusercontent.com/9263906/45940526-45d68180-bfe2-11e8-9338-edd5b2638b82.png)
![image](https://user-images.githubusercontent.com/9263906/45940539-5b4bab80-bfe2-11e8-8084-5f8a44b8f8ac.png)

2018-09-24 09:15 UTC, micahoriaso commented
<img width="688" alt="screen shot 2018-09-24 at 12 13 07" src="https://user-images.githubusercontent.com/20840601/45944557-488da280-bff3-11e8-9437-8057d8dfac93.png">
@meshack-mbuvi your response message  for a GET request for all bookmarks is not properly formatted. Please fix this

2018-09-24 09:59 UTC, meshack-mbuvi commented
@micahoriaso I have already done so

2018-09-24 10:01 UTC, micahoriaso commented
Looks good to me

2018-09-24 10:07 UTC, mikenthiwa commented
@meshack-mbuvi Check how we can represent the user as username that user id

2018-09-24 10:07 UTC, Bileonaire commented
LOOKS GOOD TO ME. Kindly resolve the return when one creates the bookmark not to return the user id. You can do that in the serializer.

2018-09-24 10:26 UTC, meshack-mbuvi commented
@Bileonaire please come help me do that

2018-09-24 14:47 UTC, Bileonaire commented
@meshack-mbuvi It is okay now

2018-09-24 16:00 UTC, mikenthiwa commented
@meshack-mbuvi looks good, Improve on test coverage

2018-09-24 16:13 UTC, parseen254 requested changes

2018-09-24 16:13 UTC, parseendavid commented on authors/apps/articles/views.py
> +    permission_classes = (IsAuthenticatedOrReadOnly, )
This should be for Authenticated Users only @meshack-mbuvi

2018-09-24 16:13 UTC, parseendavid commented on authors/apps/articles/views.py
> +    permission_classes = (IsAuthenticatedOrReadOnly, )
Let's keep this for Authenticated users only.

2018-09-25 08:54 UTC, parseen254 approved these changes

2018-09-25 09:29 UTC, merged